/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.UpdateTable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ABC
 */
public class jfBook extends javax.swing.JFrame implements ActionListener{
    public static String sql = "SELECT * FROM tblBook order by IDBook asc";

    /**
     * Creates new form jfBook
     */
    public jfBook() {
        initComponents();
        setLocationRelativeTo(null);
        UpdateTable.LoadData(sql, tblBook);
        btnBack.addActionListener(this);
        btnTimKiem.addActionListener(this);
        this.setResizable(false);
        JLabel jl = new JLabel();
        add(jl);
        jl.setSize(700, 600);

        try {
            BufferedImage image = ImageIO.read(new File("C:\\Users\\Nguye\\Documents\\NetBeansProjects\\Quanlythuvien20173302\\src\\model\\Capture.PNG"));
            int x = jl.getSize().width;
            int y = jl.getSize().height;

            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jl.setIcon(icon);
        } catch (IOException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtKeyWord = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBook = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnTimKiem = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jLabel1.setText("THÔNG TIN SÁCH CÓ TRONG THƯ VIỆN");

        jLabel2.setBackground(new java.awt.Color(204, 255, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Từ khóa:");

        txtKeyWord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtKeyWordMouseClicked(evt);
            }
        });
        txtKeyWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyWordKeyPressed(evt);
            }
        });

        tblBook.setBackground(new java.awt.Color(204, 255, 204));
        tblBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblBook);

        btnBack.setBackground(new java.awt.Color(204, 153, 0));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnBack.setText("Back");

        btnTimKiem.setBackground(new java.awt.Color(102, 255, 102));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 410, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTimKiem)
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(btnTimKiem))
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(110, 110, 110)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtKeyWordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtKeyWordMouseClicked
        // TODO add your handling code here:
        if(txtKeyWord.getText().length() == 0){
            String sqlSach1 = "SELECT * FROM tblBook";
            UpdateTable.LoadData(sqlSach1, tblBook);
        }
        else{
            String sqlSach2 = "SELECT * FROM tblBook where "
                    + "IDBook                  like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Name                 like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or KindOfBook           like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Author               like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or PublishingCompany    like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Quanlity             like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Price                like N'%"+this.txtKeyWord.getText()+"%' ";
            UpdateTable.LoadData(sqlSach2, tblBook);
        }
    }//GEN-LAST:event_txtKeyWordMouseClicked

    private void txtKeyWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyWordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_A || evt.getKeyCode() == KeyEvent.VK_S || evt.getKeyCode() == KeyEvent.VK_Q || evt.getKeyCode() == KeyEvent.VK_W || evt.getKeyCode() == KeyEvent.VK_E || evt.getKeyCode() == KeyEvent.VK_R || evt.getKeyCode() == KeyEvent.VK_T || evt.getKeyCode() == KeyEvent.VK_Y || evt.getKeyCode() == KeyEvent.VK_U || evt.getKeyCode() == KeyEvent.VK_I || evt.getKeyCode() == KeyEvent.VK_O || evt.getKeyCode() == KeyEvent.VK_P || evt.getKeyCode() == KeyEvent.VK_D ||
                evt.getKeyCode() == KeyEvent.VK_F || evt.getKeyCode() == KeyEvent.VK_G || evt.getKeyCode() == KeyEvent.VK_H || evt.getKeyCode() == KeyEvent.VK_J ||
                evt.getKeyCode() == KeyEvent.VK_K || evt.getKeyCode() == KeyEvent.VK_L || evt.getKeyCode() == KeyEvent.VK_Z || evt.getKeyCode() == KeyEvent.VK_X || evt.getKeyCode() == KeyEvent.VK_C || evt.getKeyCode() == KeyEvent.VK_V || evt.getKeyCode() == KeyEvent.VK_B ||
                evt.getKeyCode() == KeyEvent.VK_M || evt.getKeyCode() == KeyEvent.VK_ENTER ||evt.getKeyCode() == KeyEvent.VK_SPACE){
            this.btnTimKiem.doClick();
        }
    }//GEN-LAST:event_txtKeyWordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBook;
    private javax.swing.JTextField txtKeyWord;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnBack)){
            btnBackClick();
        }
        else btnTimKiemClick();
    }
    public void btnBackClick(){
        new Login().setVisible(true);
        this.dispose();
    }
    public void btnTimKiemClick(){
        if(txtKeyWord.getText().length() == 0){
            String sqlSach1 = "SELECT * FROM tblBook";
            UpdateTable.LoadData(sqlSach1, tblBook);
        }
        else{
            String sqlSach2 = "SELECT * FROM tblBook where "
                    + "IDBook                  like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Name                 like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or KindOfBook           like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Author               like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or PublishingCompany    like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Quanlity             like N'%"+this.txtKeyWord.getText()+"%' "
                    + "or Price                like N'%"+this.txtKeyWord.getText()+"%' ";
            UpdateTable.LoadData(sqlSach2, tblBook);
        }
    }
}
