/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author ABC
 */
public class jfHome extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form jfHome
     */
    public jfHome() {
        initComponents();
        setLocationRelativeTo(null);
        btnBack.addActionListener(this);
        btnQLNhanVien.addActionListener(this);
        btnQLSach.addActionListener(this);
        btnTTDocGia.addActionListener(this);
        btnTaoPhieu.addActionListener(this);
        btnTraSach.addActionListener(this);
        btnThongKe.addActionListener(this);
        this.setResizable(false);
        JLabel jl = new JLabel();
        add(jl);
        jl.setSize(700, 600);

        try {
            BufferedImage image = ImageIO.read(new File("C:\\Users\\Nguye\\Documents\\NetBeansProjects\\Quanlythuvien20173302\\src\\model\\Capture.PNG"));
            int x = jl.getSize().width;
            int y = jl.getSize().height;
     
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jl.setIcon(icon);
        } catch (IOException ex) {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnQLSach = new javax.swing.JButton();
        btnQLNhanVien = new javax.swing.JButton();
        btnTTDocGia = new javax.swing.JButton();
        btnTaoPhieu = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnTraSach = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TRANG CHỦ");

        btnQLSach.setBackground(new java.awt.Color(255, 153, 51));
        btnQLSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQLSach.setText("Quản Lý Sách");

        btnQLNhanVien.setBackground(new java.awt.Color(255, 153, 51));
        btnQLNhanVien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQLNhanVien.setText("Quản Lý Nhân Viên");

        btnTTDocGia.setBackground(new java.awt.Color(255, 153, 51));
        btnTTDocGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTTDocGia.setText("Thông Tin Độc Giả");

        btnTaoPhieu.setBackground(new java.awt.Color(255, 153, 51));
        btnTaoPhieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTaoPhieu.setText("Tạo Phiếu Mượn Sách");
        btnTaoPhieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoPhieuActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 153, 51));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");

        btnTraSach.setBackground(new java.awt.Color(255, 153, 51));
        btnTraSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTraSach.setText("Trả Sách và chi tiết mượn trả");
        btnTraSach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTraSachActionPerformed(evt);
            }
        });

        btnThongKe.setBackground(new java.awt.Color(255, 153, 51));
        btnThongKe.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTraSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTaoPhieu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(76, 138, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnQLSach, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnQLNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTTDocGia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(284, 284, 284)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(307, 307, 307)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaoPhieu)
                    .addComponent(btnQLSach))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTraSach)
                    .addComponent(btnQLNhanVien))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThongKe)
                    .addComponent(btnTTDocGia))
                .addGap(44, 44, 44)
                .addComponent(btnBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoPhieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoPhieuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTaoPhieuActionPerformed

    private void btnTraSachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTraSachActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTraSachActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongKeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JButton btnQLSach;
    private javax.swing.JButton btnTTDocGia;
    private javax.swing.JButton btnTaoPhieu;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getSource().equals(btnBack)) {
            btnBackClick();
        }
        if (e.getSource().equals(btnQLSach)) {
            btnQLSachClick();
        }
        if (e.getSource().equals(btnQLNhanVien)) {
            btnQLNhanVienClick();
        }
        if (e.getSource().equals(btnTTDocGia)) {
            btnTTDocGiaClick();
        }
        if (e.getSource().equals(btnTaoPhieu)) {
            btnTaoPhieuClick();
        }
        if (e.getSource().equals(btnTraSach)) {
            btnTraSachClick();
        }
        if (e.getSource().equals(btnThongKe)) {
            btnThongKeClick();
        }
    }

    public void btnBackClick() {
        new Login().setVisible(true);
        this.dispose();
    }

    public void btnQLSachClick() {
        new jfQLSach().setVisible(true);
        this.dispose();
    }

    public void btnQLNhanVienClick() {
        new jfQLNhanVien().setVisible(true);
        this.dispose();
    }

    public void btnTTDocGiaClick() {
        new jfTTDocGia().setVisible(true);
        this.dispose();
    }

    public void btnTaoPhieuClick() {
        new jfTaoPhieu().setVisible(true);
        this.dispose();
    }

    public void btnTraSachClick() {
        new jfTraSachThuVien().setVisible(true);
        this.dispose();
    }

    public void btnThongKeClick() {
        new jfThongKe().setVisible(true);
        this.dispose();
    }
}
