/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Connect;
import controller.DetailData;
import controller.IOFile;
import static controller.IOFile.Report;
import static controller.IOFile.exportExcel;
import controller.UpdateTable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import model.Detail;
import static view.jfTaoPhieu.idBill;
import static view.jfTaoPhieu.ngayHen1;
import static view.jfTaoPhieu.ngayMuon1;
import static view.jfTaoPhieu.tienCoc;

/**
 *
 * @author Doan Thien Duc
 */
public class jfMuonSach extends javax.swing.JFrame implements ActionListener{
    public static PreparedStatement ps;
    public static ResultSet rs;
    public int sl;
    public static String phieu;
    private String sqlChiTiet="Select b.IDBill,IDBook,IDReader,IDEmployees,NgayMuon,NgayHen,TienCoc,NgayTra,TinhTrang, TienPhat from tblBill b, tblDetailBill db\n" +
                              "Where b.IDBill=db.IDBill ";
    public String ta;
    /**
     * Creates new form jfTraSach
     */
//    public void phieu(String x){
//        this.phieu.append("\n"+this.txtIDBill.getText() + "\n");
//    }
    public jfMuonSach() {
        initComponents();
        setLocationRelativeTo(null);
        txtIDBill.setText(idBill);
        this.txtIDBill.setEnabled(false);
        LoadDataCB2();
        btnAdd.addActionListener(this);
        btnHome.addActionListener(this);
        btnInPhieu.addActionListener(this);
        btnXuatFile.addActionListener(this);
        UpdateTable.LoadData(sqlChiTiet, tblChiTiet);
        taPhieu.setText(txtIDBill.getText()+"\n");
        taPhieu.setText("TRƯỜNG ĐẠI HỌC BÁCH KHOA HÀ NỘI              "+"CỘNG HÒA XÃ HỘI CHỦ NGHĨA VIỆT NAM");
        taPhieu.setText("   Thư viện Ta Quang Bửu                        "+"Độc Lập - Tự Do - Hạnh Phúc\n\n");
        taPhieu.setText("                                                ----------------------------\n\n\n");
        taPhieu.setText("                             PHIẾU MƯỢN SÁCH\n");
        String ta=taPhieu.getText();
        taPhieu.setText(ta+"Ngày mượn:"+ngayMuon1+"\n");
        ta=taPhieu.getText();
        taPhieu.setText(ta+"Ngạy hẹn trả:"+ ngayHen1 +"\n");
        ta=taPhieu.getText();
        taPhieu.setText(ta+"Tiền cọc:"+tienCoc+ " vnđ \n");
        ta=taPhieu.getText();
        taPhieu.setText(ta+"Các mã sách mượn: \n");
        this.setResizable(false);
        JLabel jl = new JLabel();
        add(jl);
        jl.setSize(950, 750);

        try {
            BufferedImage image = ImageIO.read(new File("C:\\Users\\Nguye\\Documents\\NetBeansProjects\\Quanlythuvien20173302\\src\\model\\Capture.PNG"));
            int x = jl.getSize().width;
            int y = jl.getSize().height;

            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jl.setIcon(icon);
        } catch (IOException ex) {

        }
        
    }
    public void LoadDataCB2() {
        String sql11="Select IDBook from tblBook";
        try{
            ps = Connect.getConnect().prepareStatement(sql11);
            rs=ps.executeQuery();
            while(rs.next()){
                this.cbxIDBook.addItem(rs.getString("IDBook"));           
                }
        }catch(Exception e){
                    
                }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        cbxIDBook = new javax.swing.JComboBox<String>();
        btnAdd = new javax.swing.JButton();
        txtIDBill = new javax.swing.JTextField();
        btnHome = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        taPhieu = new javax.swing.JTextArea();
        btnInPhieu = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("MƯỢN SÁCH");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Mã phiếu:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã Sách:");

        tblChiTiet.setBackground(new java.awt.Color(204, 255, 204));
        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblChiTiet);

        cbxIDBook.setBackground(new java.awt.Color(204, 255, 204));

        btnAdd.setBackground(new java.awt.Color(204, 255, 204));
        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAdd.setText("Mượn Sách");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        txtIDBill.setBackground(new java.awt.Color(204, 255, 204));
        txtIDBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDBillActionPerformed(evt);
            }
        });

        btnHome.setBackground(new java.awt.Color(204, 255, 204));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setText("Trang chủ");

        taPhieu.setBackground(new java.awt.Color(255, 153, 51));
        taPhieu.setColumns(20);
        taPhieu.setRows(5);
        jScrollPane4.setViewportView(taPhieu);

        btnInPhieu.setBackground(new java.awt.Color(255, 153, 51));
        btnInPhieu.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnInPhieu.setText("In Phiếu");

        btnXuatFile.setBackground(new java.awt.Color(255, 153, 51));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXuatFile.setText("Xuất File");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(btnAdd))
                    .addComponent(cbxIDBook, 0, 126, Short.MAX_VALUE)
                    .addComponent(txtIDBill))
                .addGap(384, 384, 384))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(96, 96, 96)
                        .addComponent(btnInPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(286, 286, 286)
                        .addComponent(btnHome)))
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIDBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxIDBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnInPhieu, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnXuatFile, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDBillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDBillActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfMuonSach.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfMuonSach().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnInPhieu;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JComboBox<String> cbxIDBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea taPhieu;
    private javax.swing.JTable tblChiTiet;
    private javax.swing.JTextField txtIDBill;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnAdd))
            btnAddClick();
        if(e.getSource().equals(btnHome))
            btnHomeClick();
        if(e.getSource().equals(btnInPhieu))
            btnInPhieuClick();
        if(e.getSource().equals(btnXuatFile))
            btnXuatFileClick();
    }
    public void btnAddClick(){
        String sqlSL = "SELECT Quanlity FROM tblBook where IDBook= '"+this.cbxIDBook.getSelectedItem().toString()+"'";
        try{
             rs = UpdateTable.ShowTextField(sqlSL);
            if(rs.next()) sl = rs.getInt("Quanlity");
        }catch(SQLException ex){
            Logger.getLogger(jfMuonSach.class.getName()).log(Level.SEVERE, null, ex);
        };
        if(sl<1){
            JOptionPane.showMessageDialog(rootPane, "Sách đã hết", "Thông báo", 1);
        }else{
            Detail b = new Detail(this.txtIDBill.getText(),this.cbxIDBook.getSelectedItem().toString(),"Chua tra"," "," ");
            if(DetailData.addNewDetail(b)){
                ta=taPhieu.getText();
                taPhieu.setText(ta+cbxIDBook.getSelectedItem().toString()+"\n");};
            UpdateTable.LoadData(sqlChiTiet, tblChiTiet);
            String sqlSoLuong = "UPDATE tblBook SET Quanlity = ? where IDBook = ?";
            try {
            ps= Connect.getConnect().prepareStatement(sqlSoLuong);
            ps.setString(2,this.cbxIDBook.getSelectedItem().toString());
            sl -- ;
            String x =String.valueOf(sl);
            ps.setString(1, x);
            ps.execute(); 
        } catch (SQLException ex) {
            Logger.getLogger(jfMuonSach.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }
    public void btnHomeClick(){
        new jfHome().setVisible(true);
        this.dispose();
    }
    public void btnInPhieuClick(){
        phieu = this.taPhieu.getText();
        IOFile.Report();
    }
    public void btnXuatFileClick(){
        exportExcel(tblChiTiet);
    }
}
