/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import static controller.IOFile.exportExcel;
import controller.UpdateTable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Doan Thien Duc
 */
public class jfThongKe extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form jfThongKe
     */
    public jfThongKe() {
        initComponents();
        setLocationRelativeTo(null);
        btnDGMuon.addActionListener(this);
        btnDungHan.addActionListener(this);
        btnQuaHan.addActionListener(this);
        btnTacGia.addActionListener(this);
        btnNXB.addActionListener(this);
        btnSachMuon.addActionListener(this);
        btnDGQuaHan.addActionListener(this);
        btnBack.addActionListener(this);
        btnXuatFile.addActionListener(this);
        this.setResizable(false);
        JLabel jl = new JLabel();
        add(jl);
        jl.setSize(800, 600);

        try {
            BufferedImage image = ImageIO.read(new File("C:\\Users\\Nguye\\Documents\\NetBeansProjects\\Quanlythuvien20173302\\src\\model\\Capture.PNG"));
            int x = jl.getSize().width;
            int y = jl.getSize().height;
     
            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jl.setIcon(icon);
        } catch (IOException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnTacGia = new javax.swing.JButton();
        btnNXB = new javax.swing.JButton();
        btnSachMuon = new javax.swing.JButton();
        btnDGMuon = new javax.swing.JButton();
        btnDungHan = new javax.swing.JButton();
        btnQuaHan = new javax.swing.JButton();
        btnDGQuaHan = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        table.setBackground(new java.awt.Color(204, 255, 204));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("THỐNG KÊ");

        btnTacGia.setBackground(new java.awt.Color(153, 255, 153));
        btnTacGia.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTacGia.setText("Thống kê theo tác giả");

        btnNXB.setBackground(new java.awt.Color(153, 255, 153));
        btnNXB.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnNXB.setText("Thống kê theo NXB");

        btnSachMuon.setBackground(new java.awt.Color(153, 255, 153));
        btnSachMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSachMuon.setText("Thống kê lượt mượn của sách");

        btnDGMuon.setBackground(new java.awt.Color(153, 255, 153));
        btnDGMuon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDGMuon.setText("Thống kê bạn đọc mượn sách");

        btnDungHan.setBackground(new java.awt.Color(153, 255, 153));
        btnDungHan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDungHan.setText("Thống kê sách đúng hạn");

        btnQuaHan.setBackground(new java.awt.Color(153, 255, 153));
        btnQuaHan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnQuaHan.setText("Thống kê sách quá hạn");

        btnDGQuaHan.setBackground(new java.awt.Color(153, 255, 153));
        btnDGQuaHan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDGQuaHan.setText("Thống kê số lần bạn đọc quá hạn");

        btnBack.setBackground(new java.awt.Color(153, 255, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");

        btnXuatFile.setBackground(new java.awt.Color(255, 153, 51));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnXuatFile.setText("Xuất file thống kê");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(250, 250, 250)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnDGQuaHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuaHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDungHan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDGMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSachMuon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnNXB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnTacGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(327, 327, 327)
                        .addComponent(btnXuatFile)))
                .addContainerGap(272, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(btnTacGia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNXB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSachMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDGMuon)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDungHan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuaHan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDGQuaHan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnXuatFile)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDGMuon;
    private javax.swing.JButton btnDGQuaHan;
    private javax.swing.JButton btnDungHan;
    private javax.swing.JButton btnNXB;
    private javax.swing.JButton btnQuaHan;
    private javax.swing.JButton btnSachMuon;
    private javax.swing.JButton btnTacGia;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnTacGia))
            btnTacGiaClick();
        if(e.getSource().equals(btnNXB))
            btnNXBClick();
        if(e.getSource().equals(btnSachMuon))
            btnSachMuonClick();
        if(e.getSource().equals(btnDGMuon))
            btnDGMuonClick();
        if(e.getSource().equals(btnDungHan))
            btnDungHanClick();
        if(e.getSource().equals(btnQuaHan))
            btnQuaHanClick();
        if(e.getSource().equals(btnDGQuaHan))
            btnDGQuaHanClick();
        if(e.getSource().equals(btnBack))
            btnBackClick();
        if(e.getSource().equals(btnXuatFile))
            btnXuatFileClick();
    }
    public void btnTacGiaClick(){
        String sqlChung="Select Author, count(IDBook) as 'Số Lượng' From tblBook Group by Author";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnNXBClick(){
        String sqlChung="Select PublishingCompany as 'NXB', count(IDBook) as 'Số Lượng' From tblBook Group by PublishingCompany";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnSachMuonClick(){
        String sqlChung="Select Name,b.IDBook, count(IDBill) as 'Lần mượn' From tblBook b, tblDetailBill as db "
                + "Where b.IDBook=db.IDBook "
                + "Group by Name,b.IDBook "
                + "Order by count(IDBill) desc";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnDGMuonClick(){
        String sqlChung="Select Name, r.IDReader, count(IDBook) as 'Lượt mượn' From tblReader r, tblBill b, tblDetailBill db "
                + "where r.IDReader=b.IDReader "
                + "and b.IDBill=db.IDBill "
                + "Group by Name,r.IDReader "
                + "Order by count(IDBook) desc";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnDungHanClick(){
        String sqlChung="Select count(IDBook) as 'Số sách trả đúng hạn' From tblDetailBill"
                + " where TinhTrang=N'Dung han'";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnQuaHanClick(){
        String sqlChung="Select count(IDBook) as 'Số sách trả quá hạn' From tblDetailBill"
                + " where TinhTrang=N'Qua han'";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnDGQuaHanClick(){
        String sqlChung="Select Name,r.IDReader, count(IDBook) as 'Số sách trả quá hạn' From tblReader r, tblDetailBill db, tblBill b "
                + "where TinhTrang=N'Qua han' "
                + "And r.IDReader=b.IDReader "
                + "and b.IDBill=db.IDBill "
                + "Group by Name,r.IDReader "
                + "Order by count(IDBook)";
        UpdateTable.LoadData(sqlChung, table);
    }
    public void btnBackClick(){
        new jfHome().setVisible(true);
        this.dispose();
    }
    public void btnXuatFileClick(){
        exportExcel(table);
    }
}
