/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Connect;
import static controller.IOFile.exportExcel;
import controller.UpdateTable;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Doan Thien Duc
 */
public class jfTraSachThuVien extends javax.swing.JFrame implements ActionListener{
    private String sqlChiTiet="Select b.IDBill,IDBook,IDReader,IDEmployees,NgayMuon,NgayHen,TienCoc,NgayTra,TinhTrang,TienPhat from tblBill b, tblDetailBill db\n" +
                              "Where b.IDBill=db.IDBill ";
    public PreparedStatement ps;
    public  ResultSet rs;
    public PreparedStatement ps1;
    public  ResultSet rs1;
    public PreparedStatement ps2;
    public  ResultSet rs2;
    public int sl, coc;
    /**
     * Creates new form jfTraSachThuVien
     */
    public jfTraSachThuVien() {
        initComponents();
        setLocationRelativeTo(null);
        /*
        this.txtIDBill.setEnabled(false);
        this.txtIDBook.setEnabled(false);
        this.txtPhat.setEnabled(false);
        this.txtNgayMuon.setEnabled(false);
        this.txtNgayHen.setEnabled(false);
        this.txtNgayTra.setEnabled(false);
        this.txtTinhTrang.setEnabled(false);
        */
        UpdateTable.LoadData(sqlChiTiet, tblTraSach);
        btnTimKiem.addActionListener(this);
        btnTraSach.addActionListener(this);
        btnBack.addActionListener(this);
        btnXuatFile.addActionListener(this);
        this.setResizable(false);
        JLabel jl = new JLabel();
        add(jl);
        jl.setSize(850, 750);

        try {
            BufferedImage image = ImageIO.read(new File("C:\\Users\\Nguye\\Documents\\NetBeansProjects\\Quanlythuvien20173302\\src\\model\\Capture.PNG"));
            int x = jl.getSize().width;
            int y = jl.getSize().height;

            ImageIcon icon = new ImageIcon(image.getScaledInstance(x, y, image.SCALE_SMOOTH));
            jl.setIcon(icon);
        } catch (IOException ex) {

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTraSach = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtKeyWord = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtIDBill = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtIDBook = new javax.swing.JTextField();
        btnTraSach = new javax.swing.JButton();
        txtPhat = new javax.swing.JTextField();
        txtNgayMuon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtNgayHen = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtNgayTra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblTraSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTraSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTraSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTraSach);

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("TRẢ SÁCH");

        txtKeyWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtKeyWordKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Từ Khóa:");

        btnTimKiem.setBackground(new java.awt.Color(204, 255, 204));
        btnTimKiem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTimKiem.setText("Tìm kiếm");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Mã phiếu:");

        txtIDBill.setBackground(new java.awt.Color(204, 255, 204));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Mã sách:");

        txtIDBook.setBackground(new java.awt.Color(204, 255, 204));

        btnTraSach.setBackground(new java.awt.Color(204, 255, 204));
        btnTraSach.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTraSach.setText("Trả sách");

        txtNgayMuon.setBackground(new java.awt.Color(204, 255, 204));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Ngày mượn:");

        txtNgayHen.setBackground(new java.awt.Color(204, 255, 204));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Ngày hẹn trả:");

        txtNgayTra.setBackground(new java.awt.Color(204, 255, 204));
        txtNgayTra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayTraActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Ngày Trả:");

        txtTinhTrang.setBackground(new java.awt.Color(204, 255, 204));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Tình trạng:");

        btnBack.setBackground(new java.awt.Color(255, 204, 102));
        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Back");

        btnXuatFile.setBackground(new java.awt.Color(255, 204, 102));
        btnXuatFile.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnXuatFile.setText("Xuất File");

        jLabel11.setText("-------------------------------------------------------------------------------------------------------------------------------------------");

        jButton1.setBackground(new java.awt.Color(255, 153, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Tiền phạt");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel7)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2))
                                        .addGap(37, 37, 37)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(42, 42, 42))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(49, 49, 49)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDBook, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNgayHen, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDBill, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(57, 57, 57)
                        .addComponent(txtPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 92, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXuatFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTimKiem)
                            .addComponent(btnTraSach))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(365, 365, 365))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtKeyWord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTimKiem))
                .addGap(4, 4, 4)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIDBill, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtIDBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtNgayMuon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel7)
                    .addComponent(txtNgayHen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtNgayTra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTraSach)
                    .addComponent(jLabel10)
                    .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtPhat, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXuatFile)
                        .addGap(43, 43, 43)
                        .addComponent(btnBack)))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTraSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTraSachMouseClicked
        // TODO add your handling code here:
        try{
            int row = this.tblTraSach.getSelectedRow();
            String IDrow1 = (this.tblTraSach.getModel().getValueAt(row, 0)).toString();
            String IDrow2 = (this.tblTraSach.getModel().getValueAt(row, 1)).toString();
            String sql3 = "Select b.IDBill,IDBook,IDReader,IDEmployees,NgayMuon,NgayHen,TienCoc,NgayTra,TinhTrang,TienPhat from tblBill b, tblDetailBill db where b.IDBill='"+IDrow1+"'"
                    + " and IDBook='"+IDrow2+"'"
                    + " And b.IDBill=db.IDBill";
            ResultSet rs = UpdateTable.ShowTextField(sql3);
            if(rs.next()) {
                this.txtIDBill.setText(rs.getString("IDBill"));
                this.txtIDBook.setText(rs.getString("IDBook"));
                this.txtNgayMuon.setText(rs.getString("NgayMuon"));
                this.txtNgayHen.setText(rs.getString("NgayHen"));
                this.txtNgayTra.setText(rs.getString("NgayTra"));
                this.txtTinhTrang.setText(rs.getString("TinhTrang"));
        }}catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Lỗi");
        }
             
    }//GEN-LAST:event_tblTraSachMouseClicked

    private void txtNgayTraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayTraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayTraActionPerformed

    private void txtKeyWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKeyWordKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_A || evt.getKeyCode() == KeyEvent.VK_S || evt.getKeyCode() == KeyEvent.VK_Q || evt.getKeyCode() == KeyEvent.VK_W || evt.getKeyCode() == KeyEvent.VK_E || evt.getKeyCode() == KeyEvent.VK_R || evt.getKeyCode() == KeyEvent.VK_T || evt.getKeyCode() == KeyEvent.VK_Y || evt.getKeyCode() == KeyEvent.VK_U || evt.getKeyCode() == KeyEvent.VK_I || evt.getKeyCode() == KeyEvent.VK_O || evt.getKeyCode() == KeyEvent.VK_P || evt.getKeyCode() == KeyEvent.VK_D ||
                evt.getKeyCode() == KeyEvent.VK_F || evt.getKeyCode() == KeyEvent.VK_G || evt.getKeyCode() == KeyEvent.VK_H || evt.getKeyCode() == KeyEvent.VK_J ||
                evt.getKeyCode() == KeyEvent.VK_K || evt.getKeyCode() == KeyEvent.VK_L || evt.getKeyCode() == KeyEvent.VK_Z || evt.getKeyCode() == KeyEvent.VK_X || evt.getKeyCode() == KeyEvent.VK_C || evt.getKeyCode() == KeyEvent.VK_V || evt.getKeyCode() == KeyEvent.VK_B ||
                evt.getKeyCode() == KeyEvent.VK_M || evt.getKeyCode() == KeyEvent.VK_ENTER ||evt.getKeyCode() == KeyEvent.VK_SPACE){
            this.btnTimKiem.doClick();
        }
    }//GEN-LAST:event_txtKeyWordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfTraSachThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfTraSachThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfTraSachThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfTraSachThuVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfTraSachThuVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnTraSach;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTraSach;
    private javax.swing.JTextField txtIDBill;
    private javax.swing.JTextField txtIDBook;
    private javax.swing.JTextField txtKeyWord;
    private javax.swing.JTextField txtNgayHen;
    private javax.swing.JTextField txtNgayMuon;
    private javax.swing.JTextField txtNgayTra;
    private javax.swing.JTextField txtPhat;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource().equals(btnTimKiem))
            btnTimKiemClick();
        if(e.getSource().equals(btnTraSach))
            btnTraSachClick();   
        if(e.getSource().equals(btnBack))
            btnBackClick();
        if(e.getSource().equals(btnXuatFile))
            btnXuatFileClick(); 
    }
    public void btnTimKiemClick(){
        if(txtKeyWord.getText().length() == 0){
            
            UpdateTable.LoadData(sqlChiTiet, tblTraSach);
        }
        else{
            String sqlDG2 =
                    "SELECT b.IDBill,IDBook,IDReader,IDEmployees,NgayMuon,NgayHen,TienCoc,NgayTra,TienPhat from tblBill b, tblDetailBill db "
                    + " WHERE b.IDBill=db.IDBill AND"
            + "(b.IDBill                        like N'%"+this.txtKeyWord.getText()+"%' "
            + "or IDBook                        like N'%"+this.txtKeyWord.getText()+"%'"
            + "or IDReader                      like N'%"+this.txtKeyWord.getText()+"%'"
            + "or IDEmployees                   like N'%"+this.txtKeyWord.getText()+"%'"
            + "or NgayMuon                      like N'%"+this.txtKeyWord.getText()+"%')";
            UpdateTable.LoadData(sqlDG2, tblTraSach);
        }
    }
    public void btnTraSachClick(){
        java.util.Date ngayHen = null;
        long millis=System.currentTimeMillis();  
        String t="Chua tra", t1=txtNgayTra.getText();       
        java.sql.Date ngayTra=new java.sql.Date(millis); 
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");
           String ngayHenS = this.txtNgayHen.getText();
        try {
            ngayHen = formatter.parse(ngayHenS);          
        } catch (ParseException e) {
            e.printStackTrace();}
        
        if(t1.contains(t)){
            String sqlTienCoc = "SELECT TienCoc FROM tblBill where IDBill= '"+this.txtIDBill.getText()+"'";
            try{
              rs = UpdateTable.ShowTextField(sqlTienCoc);
              if(rs.next()) coc = rs.getInt("TienCoc");
               }catch(SQLException ex){
                    Logger.getLogger(jfTraSachThuVien.class.getName()).log(Level.SEVERE, null, ex);
                };
            String sqlSL = "SELECT Quanlity FROM tblBook where IDBook= '"+this.txtIDBook.getText()+"'";
            txtNgayTra.setText(formatter.format(ngayTra));
            try{
              rs = UpdateTable.ShowTextField(sqlSL);
              if(rs.next()) sl = rs.getInt("Quanlity");
               }catch(SQLException ex){
                    Logger.getLogger(jfTraSachThuVien.class.getName()).log(Level.SEVERE, null, ex);
                };
            String sqlSoLuong = "UPDATE tblBook SET Quanlity = ? where IDBook = ?";
            try {
                ps1= Connect.getConnect().prepareStatement(sqlSoLuong);
                ps1.setString(2,this.txtIDBook.getText());
                sl ++ ;
                String x =String.valueOf(sl);
                ps1.setString(1, x);
                ps1.execute(); 
                } catch (SQLException ex) {
                 Logger.getLogger(jfTraSachThuVien.class.getName()).log(Level.SEVERE, null, ex);
                   }
            String sqlNgayTra = "UPDATE tblDetailBill SET NgayTra = ?, TinhTrang=?,TienPhat=? where IDBook = ? AND IDBill=?";
            if(ngayHen.after(ngayTra)){ 
                txtTinhTrang.setText("Dung han");
                JOptionPane.showMessageDialog(null,  "Trả sách ngày: "+ txtNgayTra.getText());
            }else{txtTinhTrang.setText("Qua han");
            long diff=ngayTra.getTime()-ngayHen.getTime();
            int tre=(int) TimeUnit.DAYS.convert(diff, TimeUnit.MILLISECONDS);  
            if(Integer.parseInt(String.valueOf(tre*5000))>coc){txtPhat.setText(String.valueOf(coc));}
            else txtPhat.setText(String.valueOf(tre*5000));           
            JOptionPane.showMessageDialog(null,  "Qua han ngay: "+ txtNgayHen.getText());
            JOptionPane.showMessageDialog(null,  "Bạn bị phạt tiền!!");}
            try {
                ps2= Connect.getConnect().prepareStatement(sqlNgayTra);
                ps2.setString(4,this.txtIDBook.getText());
                ps2.setString(5, txtIDBill.getText());
                ps2.setString(1, this.txtNgayTra.getText());
                ps2.setString(2, this.txtTinhTrang.getText());
                ps2.setString(3, this.txtPhat.getText());
                ps2.execute(); 
                UpdateTable.LoadData(sqlChiTiet, tblTraSach);
                } catch (SQLException ex) {
                 Logger.getLogger(jfTraSachThuVien.class.getName()).log(Level.SEVERE, null, ex);
                   }
            
        }else JOptionPane.showMessageDialog(null, "Sách này đã được trả rồi");

    }
    public void btnBackClick(){
        new jfHome().setVisible(true);
        this.dispose();
    }
    public void btnXuatFileClick(){
        exportExcel(tblTraSach);
    }
    
}
